In [2]:
import numpy as np
import pandas as pd

# 10列 x 10行の行列
raw_data = np.random.rand(10, 10)

# DataFrameに変換
dataset = pd.DataFrame(raw_data)
dataset

0         1         2         3         4         5         6  \
0  0.838059  0.251891  0.491953  0.401585  0.404539  0.117865  0.128410   
1  0.516993  0.187754  0.503057  0.821492  0.347634  0.035669  0.103577   
2  0.275368  0.062818  0.352785  0.063736  0.105591  0.757573  0.813200   
3  0.928425  0.161506  0.542915  0.701368  0.988563  0.113988  0.486584   
4  0.378594  0.582387  0.780702  0.406218  0.432387  0.861408  0.632555   
5  0.479203  0.128055  0.840466  0.665944  0.569660  0.239248  0.503847   
6  0.722554  0.670092  0.988762  0.289567  0.376239  0.299344  0.806714   
7  0.256140  0.960290  0.582704  0.221890  0.064816  0.208639  0.735677   
8  0.010153  0.652093  0.783101  0.076559  0.148426  0.792604  0.429535   
9  0.686879  0.803110  0.502433  0.036470  0.635684  0.577284  0.885097   

          7         8         9  
0  0.270803  0.121303  0.604703  
1  0.770386  0.838838  0.861070  
2  0.919634  0.810955  0.859741  
3  0.590320  0.282214  0.928477  
4  0.318030  0.642001  0.700165  
5  0.492762  0.442161  0.172263  
6  0.509437  0.333638  0.011998  
7  0.244546  0.802917  0.767542  
8  0.482106  0.874892  0.229254  
9  0.719920  0.002528  0.180548

In [3]:
def remove_random_cell(dataframe):
    # 欠損させるindexを選ぶ
    target_index = np.random.choice(dataframe.index)

    # 欠損させるcolumnを選ぶ
    target_column = np.random.choice(dataframe.columns)

    # 欠損させる
    dataframe.loc[target_index, target_column] = None
    
# 100回実行
for _ in range(100):
    remove_random_cell(dataset)
    
dataset

0         1         2         3         4         5         6  \
0  0.838059  0.251891  0.491953  0.401585  0.404539       NaN       NaN   
1       NaN       NaN       NaN       NaN  0.347634       NaN       NaN   
2  0.275368       NaN       NaN       NaN  0.105591       NaN       NaN   
3       NaN       NaN       NaN       NaN       NaN       NaN  0.486584   
4  0.378594       NaN       NaN       NaN  0.432387       NaN       NaN   
5       NaN  0.128055       NaN       NaN       NaN       NaN       NaN   
6       NaN  0.670092       NaN  0.289567       NaN  0.299344       NaN   
7  0.256140       NaN  0.582704  0.221890       NaN       NaN       NaN   
8  0.010153  0.652093  0.783101  0.076559  0.148426       NaN       NaN   
9       NaN  0.803110  0.502433  0.036470       NaN       NaN       NaN   

          7         8         9  
0       NaN  0.121303       NaN  
1       NaN  0.838838       NaN  
2       NaN       NaN  0.859741  
3       NaN       NaN       NaN  
4       NaN  0.642001  0.700165  
5       NaN       NaN       NaN  
6  0.509437       NaN  0.011998  
7  0.244546       NaN       NaN  
8       NaN       NaN  0.229254  
9  0.719920       NaN  0.180548

In [19]:
datasets = dataset.values
# このdatasets が欠損値ある場合の入力
datasets

array([[0.83805933, 0.25189101, 0.49195316, 0.40158547, 0.40453928,
               nan,        nan,        nan, 0.12130316,        nan],
       [       nan,        nan,        nan,        nan, 0.34763429,
               nan,        nan,        nan, 0.83883837,        nan],
       [0.27536819,        nan,        nan,        nan, 0.10559092,
               nan,        nan,        nan,        nan, 0.85974108],
       [       nan,        nan,        nan,        nan,        nan,
               nan, 0.48658413,        nan,        nan,        nan],
       [0.37859427,        nan,        nan,        nan, 0.43238651,
               nan,        nan,        nan, 0.64200081, 0.70016534],
       [       nan, 0.12805509,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan],
       [       nan, 0.67009218,        nan, 0.28956684,        nan,
        0.29934438,        nan, 0.50943725,        nan, 0.01199768],
       [0.25614044,        nan, 0.5827040

In [22]:
# nanならTrue
np.isnan(datasets)

array([[False, False, False, False, False,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [False,  True,  True,  True, False,  True,  True,  True, False,
        False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False, False,  True,  True,  True, False,  True,
         True],
       [False, False, False, False, False,  True,  True,  True,  True,
        False],
       [ True, False, False, False,  True,  True,  True, False,  True,
        False]])

In [24]:
# True == 1, False == 0
a = np.where(np.isnan(datasets) == 1, 0, 1)
a

array([[1, 1, 1, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 1]])

In [18]:
# 欠損値判定 True:欠損値 があるか判定
np.any(np.isnan(datasets) == 1)

False

In [31]:
datasets[np.isnan(datasets)] = 0 
datasets * a

array([[0.83805933, 0.25189101, 0.49195316, 0.40158547, 0.40453928,
        0.        , 0.        , 0.        , 0.12130316, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.34763429,
        0.        , 0.        , 0.        , 0.83883837, 0.        ],
       [0.27536819, 0.        , 0.        , 0.        , 0.10559092,
        0.        , 0.        , 0.        , 0.        , 0.85974108],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.48658413, 0.        , 0.        , 0.        ],
       [0.37859427, 0.        , 0.        , 0.        , 0.43238651,
        0.        , 0.        , 0.        , 0.64200081, 0.70016534],
       [0.        , 0.12805509, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.67009218, 0.        , 0.28956684, 0.        ,
        0.29934438, 0.        , 0.50943725, 0.        , 0.01199768],
       [0.25614044, 0.        , 0.5827040

In [32]:
datasets

array([[0.83805933, 0.25189101, 0.49195316, 0.40158547, 0.40453928,
        0.        , 0.        , 0.        , 0.12130316, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.34763429,
        0.        , 0.        , 0.        , 0.83883837, 0.        ],
       [0.27536819, 0.        , 0.        , 0.        , 0.10559092,
        0.        , 0.        , 0.        , 0.        , 0.85974108],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.48658413, 0.        , 0.        , 0.        ],
       [0.37859427, 0.        , 0.        , 0.        , 0.43238651,
        0.        , 0.        , 0.        , 0.64200081, 0.70016534],
       [0.        , 0.12805509, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.67009218, 0.        , 0.28956684, 0.        ,
        0.29934438, 0.        , 0.50943725, 0.        , 0.01199768],
       [0.25614044, 0.        , 0.5827040

In [33]:
np.nan*0

nan

In [34]:
arr = np.random.randint(4, 10, 3)

In [35]:
arr

array([6, 7, 5])